### ISSUE TITLE
it reports that the DEFAULT_ICON can not be found

### ISSUE THREAD

**Issue by KGB121** [CowNowK/AimStarCS2#1]

**Comment by CowNowK** [comment]
I might have forgotten to upload the icon file. You can right-click on the project and go to "Add Resources" to modify the icon file.

**Comment by KGB121** [comment]
the latest version reports about 12 mistakes

**Comment by CowNowK** [comment]
> the latest version reports about 12 mistakes

@KGB121 Can you provide a screenshot of the mistakes? It's possible that I missed some unuploaded changes.

**Comment by Laidbak83** [comment]
Got same error to compil project I cannot compile it 

Can you make release on git

**Comment by CowNowK** [comment]
> Got same error to compil project I cannot compile it 
> 
> Can you make release on git 

@Laidbak83 Is it the lastest commit?

**Comment by Laidbak83** [comment]
Sorry ?

**Comment by Laidbak83** [comment]
Wdym ?

**Comment by CowNowK** [comment]
> Wdym ?

Synchronize all files.

**Comment by Laidbak83** [comment]
Take my discord 
I will show you de error 
laidbak
