### ISSUE TITLE
Your config saver has a issue

### ISSUE THREAD

**Issue by Fr0go1** [CowNowK/AimStarCS2#15]
https://github.com/CowNowK/AimStarCS2/blob/1b9e234281895ce8942f584c9f4a8ae2e7e95fd3/CS2_External/Utils/ConfigSaver.cpp#L100C27-L100C27

refer to the link above,

the code needs to all be like "setting " not like "setting". you need the space in between the end of the saving setting and the ".

**Comment by CowNowK** [comment]
Thank you for your reminder. I was careless and didn't notice this detail.
