### ISSUE TITLE
bug in version:2.5

### ISSUE THREAD

**Issue by tppp2806** [CowNowK/AimStarCS2#17]
This is a amzing project,but
The **fov of the aimbot  in version 2.5** is not effective.

**Comment by tppp2806** [comment]
自从2.4b版本之后，改变了aimbot的功能“现在瞄准机器人正在使用鼠标，并且无法检测到”，导致了aimbot限制fov瞄准范围失效

**Comment by hw0ld** [comment]
keep an eye on updates, the fix will be soon (most likely already in version 2.7)

**Comment by hw0ld** [comment]
> This is a amzing project,but The **fov of the aimbot in version 2.5** is not effective.
keep an eye on updates, the fix will be soon (most likely already in version 2.7)

**Comment by hw0ld** [comment]
> This is a amzing project,but The **fov of the aimbot in version 2.5** is not effective.

keep an eye on updates, the fix will be soon (most likely already in version 2.7)
