### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by myjoker003** [CowNowK/AimStarCS2#18]
Build started...
1>------ Build started: Project: CS2_External, Configuration: Debug x64 ------
1>Bone.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>Cheats.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(20,22): warning C4305: 'initializing': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(40,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(41,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(47,18): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(51,14): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,43): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,34): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(35,41): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(56,16): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(162,46): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(183,36): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(200,57): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(201,19): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(203,70): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(249,20): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(251,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(252,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(253,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(273,20): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(275,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(276,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(277,23): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(377,22): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(409,34): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(461,22): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Render.hpp(493,34): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Features\ESP.h(46,79): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Features\ESP.h(50,59): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Cheats.cpp(516,58): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Cheats.cpp(516,27): warning C4244: 'argument': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>Entity.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>Mouse.cpp
1>Game.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>main.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(20,22): warning C4305: 'initializing': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(40,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(41,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(47,18): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(51,14): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,43): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,34): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\main.cpp(95,31): warning C4101: 'e': unreferenced local variable
1>Offsets.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(33,35): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(39,46): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(45,31): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(51,35): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(59,43): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(65,48): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Offsets.cpp(71,41): warning C4244: '=': conversion from 'DWORD64' to 'DWORD', possible loss of data
1>imgui.cpp
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx11.cpp
1>imgui_impl_win32.cpp
1>imgui_tables.cpp
1>imgui_widgets.cpp
1>OS-ImGui.cpp
1>OS-ImGui_Base.cpp
1>OS-ImGui_External.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>Radar.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(8,89): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(9,89): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(62,17): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(64,62): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(65,42): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(147,28): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(148,28): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(167,6): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(176,63): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(177,105): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(177,57): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(179,34): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(180,34): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(182,36): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(183,36): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(185,36): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Radar\Radar.cpp(186,36): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>TriggerBot.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>ConfigMenu.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(20,22): warning C4305: 'initializing': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(40,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(41,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(47,18): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(51,14): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,43): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,34): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ConfigMenu.cpp(45,97): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>Generating Code...
1>Compiling...
1>ConfigSaver.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(20,22): warning C4305: 'initializing': truncation from 'double' to 'float'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(40,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(41,21): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(47,18): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(51,14): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,43): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\AimBot.hpp(121,34): warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data
1>GlobalVars.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>MemorySearch.cpp
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(8,1): warning C4005: '_is_invalid': macro redefinition
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\ProcessManager.hpp(7,1): message : see previous definition of '_is_invalid'
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(23,28): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(38,22): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(40,26): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(44,35): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(49,29): warning C4018: '>=': signed/unsigned mismatch
1>C:\Users\Administrator\Desktop\AimStarCS2-master\CS2_External\Utils\MemorySearch.cpp(91,101): warning C4244: 'argument': conversion from 'SIZE_T' to 'DWORD', possible loss of data
1>Generating Code...
1>Cheats.obj : error LNK2019: unresolved external symbol __imp_PlaySoundW referenced in function "void __cdecl HitSound::Run(class CEntity const &,int &)" (?Run@HitSound@@YAXAEBVCEntity@@AEAH@Z)
1>C:\Users\Administrator\Desktop\AimStarCS2-master\x64\Debug\CS2_External.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "CS2_External.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 2:17 AM and took 41.084 seconds ==========

**Comment by CowNowK** [comment]
Include winmm.lib in your linker input
