### ISSUE TITLE
some problems with function

### ISSUE THREAD

**Issue by dky718918** [CowNowK/AimStarCS2#2]
First, How to use the bunnyhop function. 
Then, what do the three parameters of RCS: start bullet, yaw, and pitch mean?

thanks for your answer

**Comment by CowNowK** [comment]
Bunnyhop's code seems to have some errors. I haven't fixed them yet.
StartBullet is when recoil control starts after firing the Nth bullet. (N<=6)
Yaw and Pitch determine the magnitude of control.

> Due to extensive code modifications, merging with the original repository is not possible. Currently, I haven't identified the code causing the error. If you have the ability, please try to help me locate it and provide feedback. Thanks

**Comment by dky718918** [comment]
So the smaller the value of startbullet, the better,right?
and the larger the value of yaw and pitch, the better, right?

**Comment by CowNowK** [comment]
> So the smaller the value of startbullet, the better,right? and the larger the value of yaw and pitch, the better, right?

@dky718918 I think so. Startbullet determines when to start controlling recoil. The larger the values of Yaw and Pitch, the more concentrated the bullets' trace.

**Comment by Laidbak83** [comment]
Maybe a discord is better to manage issues ?

**Comment by dky718918** [comment]
thanks for your answer

**Comment by CowNowK** [comment]
@dky718918 bhop fixed.
