### ISSUE TITLE
Getting these 2 errors while compiling and opening the compiled cheat.

### ISSUE THREAD

**Issue by LeonRyan1** [CowNowK/AimStarCS2#23]
1st one is this i got while compiling in studio:
Cheats.obj : error LNK2019: unresolved external symbol __imp_PlaySoundW referenced in function "void __cdecl HitSound::Run(class CEntity const &,int &)" (?Run@HitSound@@YAXAEBVCEntity@@AEAH@Z)
1>D:\AimStarCS2-master\AimStarCS2-master\x64\Debug\CS2_External.exe : fatal error LNK1120: 1 unresolved externals

-----------------------------------------------------------------------------------------------------------------------------------

I still compiled after removing the hitsound stuff and after the cheat got compiled i got this error while opening the cheat:

Assertion failed: SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!", file D:\Games\CS\CS2 Externals\AimStarCS2-master\AimStarCS2-master\CS2_External\OS-ImGui\imgui\imgui.cpp, line 9273

i still removed the code in that line and cheat worked, btw the code at that line was this:
IM_ASSERT(SizeOfIDStack         == window->IDStack.Size     && "PushID/PopID or TreeNode/TreePop Mismatch!");

**Comment by CowNowK** [comment]
![image](https://github.com/CowNowK/AimStarCS2/assets/133740174/535e927e-39f5-4a74-a623-da0feb60fd3a)
