### ISSUE TITLE
TriggerBot always mode

### ISSUE THREAD

**Issue by Laidbak83** [CowNowK/AimStarCS2#3]
Hello 1st thanks for your job :) 

2nd how to not put a key for trigger ? 

Like trigger always activate 

When I put my cursor on enemy trigger fire auto

**Comment by CowNowK** [comment]
@Laidbak83 Thank you for your feedback. I will add this option later

**Comment by Laidbak83** [comment]
Thanks

**Comment by Laidbak83** [comment]
Thx for update ✅

**Comment by CowNowK** [comment]
ima sry sth went wrong
You can add me on discord: imcownow
