### ISSUE TITLE
Triggerbot

### ISSUE THREAD

**Issue by BrowarPL** [CowNowK/AimStarCS2#31]
Hi,

Triggerbot is shooting 5 bullrts at at time with any automatic weapon. For most cases it's causing problems with hitting targets.

For now I've modified the Triggerbot function with 

`mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0);`

so it's shooting one bullet at a time, which seems to be much more accurate. 

Is it any way you can add for how long the Triggerbot would press the left mouse button, as this would make it easier to use. 

I can understand, analyze and slightly modify the code, but due to my lack of programming skills, I'm unable to make new functions.

Mode: All
Severity: Low

**Comment by CowNowK** [comment]
You should check the fake shot

**Comment by CowNowK** [comment]
Set the fake shot to 0ms to one tap

**Comment by BrowarPL** [comment]
Thank you for your reply. Around 100-110ms works well for me. Keep up the great work :)
