### ISSUE TITLE
visible check on filled boxes 

### ISSUE THREAD

**Issue by keysCodes** [CowNowK/AimStarCS2#33]
this would be great

**Comment by CowNowK** [comment]
You can make it by ur self, it is ez
`ESP.h`

**Comment by keysCodes** [comment]
ESP.h does not help me make it by myself bru

**Comment by OvertimeDev-Random** [comment]
you can legit just copy and paste the vis check code for filled boxes

**Comment by keysCodes** [comment]
source?
