### ISSUE TITLE
cheat down?

### ISSUE THREAD

**Issue by zeroy2891** [CowNowK/AimStarCS2#38]

**Comment by evrope** [comment]
aimbot not working

**Comment by mattjax16** [comment]
Anyone have any ideas why nothing looks weird from the last few commit

**Comment by F1ghter42** [comment]
game got updated, offsets changed. wait for cheat update.

**Comment by mattjax16** [comment]
> game got updated, offsets changed. wait for cheat update.

Oh ya I see the offset already got changed upstream

**Comment by evrope** [comment]
> aimbot not working

i fixed aimbot. if anyone need fixed version send me discord name or telegram

**Comment by ccq1111** [comment]
> > Aimbot 不工作
> 
> 我修复了 aimbot。如果有人需要固定版本，请向我发送不和谐名称或电报
qq?154784334 plz ._.

**Comment by evrope** [comment]
> offsets updated

bunny not work
