### ISSUE TITLE
Can't Run after building Error with OS-ImGui

### ISSUE THREAD

**Issue by kennyS-69420** [CowNowK/AimStarCS2#40]
After I build the project and try and run it I get this error.

Assertion failed: SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!", file C:\Users\USER\Documents\Coding\Game-Hacks\CS2\AimStarCS2\CS2_External\OS-ImGui\imgui\imgui.cpp, line 9273

Curious as to what is causing it as I can build and run CS2_External (upstream repo) just fine.

**Comment by evrope** [comment]
> After I build the project and try and run it I get this error.
> 
> Assertion failed: SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!", file C:\Users\USER\Documents\Coding\Game-Hacks\CS2\AimStarCS2\CS2_External\OS-ImGui\imgui\imgui.cpp, line 9273
> 
> Curious as to what is causing it as I can build and run CS2_External (upstream repo) just fine.

try to build release/x64

**Comment by kennyS-69420** [comment]
This worked thank you!
