### ISSUE TITLE
ESP laggy while tabbed in but when i alt tab or press escape it is fixed

### ISSUE THREAD

**Issue by goyoplayer** [CowNowK/AimStarCS2#5]
title says it all, when im in game, esp is super laggy and wont work right but when i press esc or tab out it fixes it

**Comment by CowNowK** [comment]
> title says it all, when im in game, esp is super laggy and wont work right but when i press esc or tab out it fixes it

@goyoplayer external suck is unavoidable
Even with the use of multithreading, there won't be much difference
