### ISSUE TITLE
fix laggy box

### ISSUE THREAD

**Issue by Tempfyyyy** [CowNowK/AimStarCS2#6]
it is when im using 60 fps then the esp works fine but if i go to 165hz or anything over 60 fps it starting to delay i think because the render is locked at 60 fps !

**Comment by CowNowK** [comment]
> it is when im using 60 fps then the esp works fine but if i go to 165hz or anything over 60 fps it starting to delay i think because the render is locked at 60 fps !

@Tempfyyyy This is external cheating, and it is unavoidable. External cheating utilizes API reading, while internal cheating uses pointer reading, and there is a significant difference in efficiency between these two ways.

**Comment by Tempfyyyy** [comment]
@CowNowK how did i cheat.io did it then ?

**Comment by CowNowK** [comment]
> @CowNowK how did icheat.io did it then ? 
> 

idk how it work and idk how to fix it sry
