### ISSUE TITLE
fullscreen 

### ISSUE THREAD

**Issue by Tempfyyyy** [CowNowK/AimStarCS2#7]
please draw the menu and esp and that stuff over steamoverlay like icheat.io it did that you can play on fullscreen and see all

**Comment by MagonYT** [comment]
im pretty sure thats detected by VAC

**Comment by Tempfyyyy** [comment]
No I don’t think so I played with icheat.io 20 hours with 0 smoothing on
the aimbot and I have 0 vac band (I shot trough walls and smokes)

MagonYT ***@***.***> schrieb am So. 15. Okt. 2023 um 21:16:
