### ISSUE TITLE
VAC Banned

### ISSUE THREAD

**Issue by MagonYT** [CowNowK/AimStarCS2#8]
this isnt less of an issue, more of a comment, i got vac banned even though I only used ESP, if you could, try a different method of ESP.

**Comment by Soduem** [comment]
It's overwatch lol, this is undet since it is an external.

**Comment by CowNowK** [comment]
@MagonYT it is overwatch ban not a vac detection

**Comment by kennyS-69420** [comment]
Is  there even overwatch rn in cs2 tho?
